
# when using links need to prefix that everywhere
# for github pages
BASE_URL = "/tesla-megapack-tracker/"
# locally
# BASE_URL = "/"

def generate_link(ip):
    return BASE_URL + ip.lstrip("/")


VALID_STATUS = ("planning", "construction", "operation")

COUNTRY_EMOJI_DI = {
    "usa": "🇺🇸", 
    "australia": "🇦🇺",
    "uk": "🇬🇧",
    "korea": "🇰🇷",
    "philippines": "🇵🇭",
    "germany": "🇩🇪",
    "france": "🇫🇷",
    "italy": "🇮🇹",
}

US_STATES_LONG_TO_SHORT = {
    "alabama" :"AL",
    "alaska" :"AK",
    "arizona" :"AZ",
    "arkansas" :"AR",
    "california" :"CA",
    "colorado" :"CO",
    "connecticut" :"CT",
    "delaware" :"DE",
    "florida" :"FL",
    "georgia" :"GA",
    "hawaii" :"HI",
    "idaho" :"ID",
    "illinois" :"IL",
    "indiana" :"IN",
    "iowa" :"IA",
    "kansas" :"KS",
    "kentucky" :"KY",
    "louisiana" :"LA",
    "maine" :"ME",
    "maryland" :"MD",
    "massachusetts" :"MA",
    "michigan" :"MI",
    "minnesota" :"MN",
    "mississippi" :"MS",
    "missouri" :"MO",
    "montana" :"MT",
    "nebraska" :"NE",
    "nevada" :"NV",
    "new hampshire" :"NH",
    "new jersey" :"NJ",
    "new mexico" :"NM",
    "new york" :"NY",
    "north carolina" :"NC",
    "north dakota" :"ND",
    "ohio" :"OH",
    "oklahoma" :"OK",
    "oregon" :"OR",
    "pennsylvania" :"PA",
    "rhode island" :"RI",
    "south carolina" :"SC",
    "south dakota" :"SD",
    "tennessee" :"TN",
    "texas" :"TX",
    "utah" :"UT",
    "vermont" :"VT",
    "virginia" :"VA",
    "washington" :"WA",
    "west virginia" :"WV",
    "wisconsin" :"WI",
    "wyoming" :"WY",
}

US_STATES_SHORT_TO_LONG = {
    "AL": "alabama",
    "AK": "alaska",
    "AZ": "arizona",
    "AR": "arkansas",
    "CA": "california",
    "CO": "colorado",
    "CT": "connecticut",
    "DE": "delaware",
    "FL": "florida",
    "GA": "georgia",
    "HI": "hawaii",
    "ID": "idaho",
    "IL": "illinois",
    "IN": "indiana",
    "IA": "iowa",
    "KS": "kansas",
    "KY": "kentucky",
    "LA": "louisiana",
    "ME": "maine",
    "MD": "maryland",
    "MA": "massachusetts",
    "MI": "michigan",
    "MN": "minnesota",
    "MS": "mississippi",
    "MO": "missouri",
    "MT": "montana",
    "NE": "nebraska",
    "NV": "nevada",
    "NH": "new hampshire",
    "NJ": "new jersey",
    "NM": "new mexico",
    "NY": "new york",
    "NC": "north carolina",
    "ND": "north dakota",
    "OH": "ohio",
    "OK": "oklahoma",
    "OR": "oregon",
    "PA": "pennsylvania",
    "RI": "rhode island",
    "SC": "south carolina",
    "SD": "south dakota",
    "TN": "tennessee",
    "TX": "texas",
    "UT": "utah",
    "VT": "vermont",
    "VA": "virginia",
    "WA": "washington",
    "WV": "west virginia",
    "WI": "wisconsin",
    "WY": "wyoming",
}